apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    monitor: "true"
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
    - port: web